version: '3.3'
services:
  writeDb:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: 'writeDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - write-db-data:/var/lib/mysql

  readDb:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: 'readDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - read-db-data:/var/lib/mysql

  inMemoryDb:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

volumes:
  write-db-data:
  read-db-data:
